### ISSUE TITLE
No module named 'trio'

### ISSUE THREAD

**Issue by BigRusBoss** [megadose/holehe-maltego#2]
Hello. Thank you for your plugin. There is such a problem.

https://i.imgur.com/ORJI8hg.png

Windows 7 SP1 x64, python 3.8.6

How do I install this module?

**Comment by sai84** [comment]
> Hello. Thank you for your plugin. There is such a problem.
> 
> https://i.imgur.com/ORJI8hg.png
> 
> Windows 7 SP1 x64, python 3.8.6
> 
> How do I install this module?

The same problem on Windows 10

**Comment by sai84** [comment]
> Hello. Thank you for your plugin. There is such a problem.
> 
> https://i.imgur.com/ORJI8hg.png
> 
> Windows 7 SP1 x64, python 3.8.6
> 
> How do I install this module?

Solved. Just install this module. 
pip install trio
